-----------------------------------------------------
-- Conectarse con el usuario SITD
-----------------------------------------------------
-- CONNECT SITD/SITD123;

-----------------------------------------------------
-- Crear tabla de películas y series
-----------------------------------------------------

CREATE TABLE CATALOGO_ENTRETENIMIENTO (
    ID_CONTENIDO      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TITULO            VARCHAR2(200)       NOT NULL,
    TIPO              VARCHAR2(20)        NOT NULL,
    GENERO            VARCHAR2(100),
    ANIO_ESTRENO      NUMBER(4),
    DIRECTOR          VARCHAR2(150),
    DURACION_MIN      NUMBER(4),
    PAIS_ORIGEN       VARCHAR2(100),
    CLASIFICACION     VARCHAR2(20),
    IDIOMA_ORIGINAL   VARCHAR2(50),
    PLATAFORMA        VARCHAR2(100),
    CALIFICACION      NUMBER(3,1),
    DISPONIBLE        CHAR(1) DEFAULT 'S',
    FECHA_REGISTRO    DATE DEFAULT SYSDATE,
    
    CONSTRAINT PK_CATALOGO_ENTRETENIMIENTO
        PRIMARY KEY (ID_CONTENIDO),

    CONSTRAINT CK_TIPO_CONTENIDO
        CHECK (TIPO IN ('PELICULA', 'SERIE')),

    CONSTRAINT CK_DISPONIBLE
        CHECK (DISPONIBLE IN ('S', 'N'))
);

SELECT * FROM catalogo_entretenimiento;